# Generated by Django 3.2.5 on 2023-01-12 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_terrain'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='terrain',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.terrain'),
            preserve_default=False,
        ),
    ]
