# Generated by Django 3.2.5 on 2023-01-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('F', 'Foot Ball'), ('B', 'Basket Ball'), ('T', 'Tennis'), ('H', 'Hand Ball')], max_length=5, unique=True),
        ),
    ]
