# Generated by Django 3.2.5 on 2023-01-13 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='api.type'),
            preserve_default=False,
        ),
    ]
