# Generated by Django 4.1.5 on 2023-01-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_type_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="terrain",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="terrain",
            name="price",
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
